### PR TITLE
Updated to gradle 6.8 and api 30 and changed Option1.java

### PR DESCRIPTION
**Pull request by p2kr**
Updated to Gradle 6.8 and Android API 30.  @Riku32 Please send some guidelines for editing more, I will be working on this project for about a month.

### CODE REVIEW

**Comment by p2kr** [comment]
Changes vidstream to gogo-stream

**Comment by Riku32** [comment]
Alright, I've been thinking about rewriting the whole thing to be cross-platform, ill let you make updates on legacy for now though.

**Comment by p2kr** [comment]
@Riku32 Please build the apk for now

**Comment by Riku32** [comment]
@p2kr currently not in a place where java dev environment is setup, would you mind pushing a github actions to automatically build and push a release? If not then ill do it but a bit later.

**Comment by p2kr** [comment]
> @p2kr currently not in a place where java dev environment is setup, would you mind pushing a github actions to automatically build and push a release? If not then ill do it but a bit later.

@Riku32 I don't have the authority/permission to create GitHub workflows

**Pull request merged**
